# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-MoCo
version:      0.17
version_from: lib/DBIx/MoCo.pm
installdirs:  site
requires:
    Cache::Memory:                 0
    Class::Trigger:                0
    Data::Dumper:                  0
    DateTime:                      0
    DateTime::Format::MySQL:       0
    DBD::SQLite:                   0
    DBI:                           0
    Exporter:                      0
    File::Spec:                    0
    FormValidator::Simple:         0
    List::MoreUtils:               0
    List::Util:                    0
    Math::BigInt::Lite:            0
    Net::Address::Ethernet:        0
    Scalar::Util:                  0
    SQL::Abstract:                 0
    Storable:                      0
    Test::Class:                   0
    Tie::IxHash:                   0
    Time::HiRes:                   0
    UNIVERSAL::require:            0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
